
  List chineseApp = [
    {
      "cApp": "Xender",
      "altApp1": "Jio Switch",
      "altApp1Link": "com.reliance.jio.jioswitch",
      "altApp2": "Share All",
      "altApp2Link":
          "com.loku.parralel.share.data.filetransfer.sharing.free",
      "cIcon": "assets/icons/xender.png",
      "altApp1Icon": "assets/icons/jioswitch.png",
      "altApp2Icon": "assets/icons/shareall.png",
    },
    {
      "cApp": "SHAREit",
      "altApp1": "Jio Switch",
      "altApp1Link": "com.reliance.jio.jioswitch",
      "altApp2": "Share All",
      "altApp2Link":
          "com.loku.parralel.share.data.filetransfer.sharing.free",
      "cIcon": "assets/icons/shareit.png",
      "altApp1Icon": "assets/icons/jioswitch.png",
      "altApp2Icon": "assets/icons/shareall.png",
    },
    {
      "cApp": "CamScanner",
      "altApp1": "Doc Scanner",
      "altApp1Link": "net.doc.scanner",
      "altApp2": "Adobe Scanner",
      "altApp2Link": "com.adobe.scan.android",
      "cIcon": "assets/icons/camscanner.png",
      "altApp1Icon": "assets/icons/docscanner.png",
      "altApp2Icon": "assets/icons/adobe_scanner.png",
    },
    {
      "cApp": "UC Browser",
      "altApp1": "Jio Browser",
      "altApp1Link": "com.jio.web",
      "altApp2": "Epic Browser",
      "altApp2Link": "com.epic.browser",
      "cIcon": "assets/icons/ucbrowser.png",
      "altApp1Icon": "assets/icons/jiobrowser.png",
      "altApp2Icon": "assets/icons/epic_browser.png",
    },
    {
      "cApp": "TikTok",
      "altApp1": "Roposo",
      "altApp1Link": "com.roposo.android",
      "altApp2": "Dumbsmash",
      "altApp2Link": "com.mobilemotion.dubsmash",
      "cIcon": "assets/icons/tiktok.png",
      "altApp1Icon": "assets/icons/roposo.png",
      "altApp2Icon": "assets/icons/dumbsmash.png",
    },
    {
      "cApp": "Helo",
      "altApp1": "Roposo",
      "altApp1Link": "com.roposo.android",
      "altApp2": "Dumbsmash",
      "altApp2Link": "com.mobilemotion.dubsmash",
      "cIcon": "assets/icons/helo.png",
      "altApp1Icon": "assets/icons/roposo.png",
      "altApp2Icon": "assets/icons/dumbsmash.png",
    },
    {
      "cApp": "Likee",
      "altApp1": "Roposo",
      "altApp1Link": "com.roposo.android",
      "altApp2": "Dumbsmash",
      "altApp2Link": "com.mobilemotion.dubsmash",
      "cIcon": "assets/icons/like.png",
      "altApp1Icon": "assets/icons/roposo.png",
      "altApp2Icon": "assets/icons/dumbsmash.png",
    },
    {
      "cApp": "Club Factory",
      "altApp1": "Tata Cliq",
      "altApp1Link": "com.tul.tatacliq",
      "altApp2": "Flipkart",
      "altApp2Link": "com.flipkart.android",
      "cIcon": "assets/icons/clubfactory.png",
      "altApp1Icon": "assets/icons/tatacliq.png",
      "altApp2Icon": "assets/icons/flipkart.png",
    },
    {
      "cApp": "U-Dictonary",
      "altApp1": "Merriam-Webster Dictonary",
      "altApp1Link": "com.merriamwebster",
      "altApp2": "Oxford Hindi Dictionary",
      "altApp2Link":
          "com.mobisystems.msdict.embedded.wireless.oxford.hindi",
      "cIcon": "assets/icons/udictionary.png",
      "altApp1Icon": "assets/icons/MWdictionary.png",
      "altApp2Icon": "assets/icons/englishhindidictionary.png",
    },
    {
      "cApp": "VivaVideo",
      "altApp1": "Photo Video Maker",
      "altApp1Link": "com.funcamerastudio.videomaker",
      "altApp2": "FilmoraGo",
      "altApp2Link": "com.wondershare.filmorago",
      "cIcon": "assets/icons/viva.png",
      "altApp1Icon": "assets/icons/photovideomaker.png",
      "altApp2Icon": "assets/icons/filmorago.png",
    },
    {
      "cApp": "Beauty Plus",
      "altApp1": "LightX Photo Editor",
      "altApp1Link": "com.lightx",
      "altApp2": "PicsArt",
      "altApp2Link": "com.picsart.studio",
      "cIcon": "assets/icons/beautyplus.png",
      "altApp1Icon": "assets/icons/lightxphotoeditor.png",
      "altApp2Icon": "assets/icons/picsart.png",
    },
//    {
//      "cApp": "PUBG MOBILE",
//      "altApp1": "Call of Duty (COD)",
//      "altApp1Link": "com.activision.callofduty.shooter",
//      "altApp2": "Free Fire",
//      "altApp2Link": "com.dts.freefireth",
//      "cIcon": "assets/icons/pubg.png",
//      "altApp1Icon": "assets/icons/cod.png",
//      "altApp2Icon": "assets/icons/freefire.png",
//    }
  ];